// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/contacts": {
            "get": {
                "description": "List contacts",
                "tags": [
                    "contact"
                ],
                "summary": "List Contacts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number, start from 1.",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.Pack-resp_PagingPack-m_ContactVo"
                        }
                    }
                }
            },
            "post": {
                "description": "send mail",
                "tags": [
                    "contact"
                ],
                "summary": "Add contact",
                "parameters": [
                    {
                        "description": "add contact form",
                        "name": "HTTP_POST_body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form.AddContactForm"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/resp.Pack-resp_None"
                        }
                    }
                }
            }
        },
        "/api/v1/contacts/any/batch-deletions": {
            "post": {
                "description": "Delete contacts in batch",
                "tags": [
                    "contact"
                ],
                "summary": "Delete Contacts In Batch",
                "parameters": [
                    {
                        "description": "batch deletion ID list",
                        "name": "HTTP_POST_body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.Pack-resp_None"
                        }
                    }
                }
            }
        },
        "/api/v1/contacts/{id}": {
            "delete": {
                "description": "Delete contact",
                "tags": [
                    "contact"
                ],
                "summary": "Delete Contact",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "contact ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.Pack-resp_None"
                        }
                    }
                }
            }
        },
        "/api/v1/sent-mails": {
            "get": {
                "description": "List sent mails",
                "tags": [
                    "mail"
                ],
                "summary": "List Sent Mails",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number, start from 1.",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.Pack-resp_PagingPack-m_SentMailVo"
                        }
                    }
                }
            },
            "post": {
                "description": "send mail",
                "tags": [
                    "mail"
                ],
                "summary": "Send mail",
                "parameters": [
                    {
                        "description": "send mail form",
                        "name": "HTTP_POST_body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form.SendMailForm"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/resp.Pack-resp_None"
                        }
                    }
                }
            }
        },
        "/api/v1/sent-mails/any/batch-deletions": {
            "post": {
                "description": "Delete sent mails in batch",
                "tags": [
                    "mail"
                ],
                "summary": "Delete Sent Mails In Batch",
                "parameters": [
                    {
                        "description": "batch deletion ID list",
                        "name": "HTTP_POST_body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.Pack-resp_None"
                        }
                    }
                }
            }
        },
        "/api/v1/sent-mails/{id}": {
            "delete": {
                "description": "Delete sent mail",
                "tags": [
                    "mail"
                ],
                "summary": "Delete Sent Mail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "sent mail ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.Pack-resp_None"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "_const.MailType": {
            "type": "string",
            "enum": [
                "plain mail",
                "registered mail",
                "plain postcard",
                "registered postcard",
                "plain presswork",
                "registered presswork",
                "post package",
                "post express package",
                "post small package"
            ],
            "x-enum-comments": {
                "MailTypeExpressPackage": "包裹：快递",
                "MailTypePackage": "包裹：一般",
                "MailTypePlainMail": "信件：一般",
                "MailTypePlainPostcard": "明信片：一般",
                "MailTypePlainPresswork": "印刷品：一般",
                "MailTypeRegisteredMail": "信件：挂号",
                "MailTypeRegisteredPostcard": "明信片：挂号",
                "MailTypeRegisteredPresswork": "印刷品：挂号",
                "MailTypeSmallPackage": "包裹：小包"
            },
            "x-enum-varnames": [
                "MailTypePlainMail",
                "MailTypeRegisteredMail",
                "MailTypePlainPostcard",
                "MailTypeRegisteredPostcard",
                "MailTypePlainPresswork",
                "MailTypeRegisteredPresswork",
                "MailTypePackage",
                "MailTypeExpressPackage",
                "MailTypeSmallPackage"
            ]
        },
        "_const.PostFeePaymentType": {
            "type": "string",
            "enum": [
                "cash",
                "stamps"
            ],
            "x-enum-comments": {
                "PostFeePaymentTypeCash": "现金",
                "PostFeePaymentTypeStamps": "邮票"
            },
            "x-enum-varnames": [
                "PostFeePaymentTypeCash",
                "PostFeePaymentTypeStamps"
            ]
        },
        "_const.PostRegion": {
            "type": "string",
            "enum": [
                "domestic local",
                "domestic",
                "overseas (by air)",
                "overseas (surface)",
                "overseas (by air surface)"
            ],
            "x-enum-comments": {
                "PostRegionDomestic": "国内外埠",
                "PostRegionDomesticLocal": "国内本埠",
                "PostRegionOverseasByAir": "跨洋航空",
                "PostRegionOverseasByAirAndSurface": "跨洋航空水陆路",
                "PostRegionOverseasSurface": "跨洋水陆路"
            },
            "x-enum-varnames": [
                "PostRegionDomesticLocal",
                "PostRegionDomestic",
                "PostRegionOverseasByAir",
                "PostRegionOverseasSurface",
                "PostRegionOverseasByAirAndSurface"
            ]
        },
        "_const.RecipientType": {
            "type": "string",
            "enum": [
                "myself",
                "couple",
                "relative",
                "friend",
                "pen pal",
                "postmark collecting",
                "other"
            ],
            "x-enum-varnames": [
                "RecipientTypeMyself",
                "RecipientTypeCouple",
                "RecipientTypeRelative",
                "RecipientTypeFriend",
                "RecipientTypePenPal",
                "RecipientTypePostmarkCollecting",
                "RecipientTypeOther"
            ]
        },
        "form.AddContactForm": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "CaotangLu 1 Hao"
                },
                "address_secret_part": {
                    "type": "string",
                    "example": "1 Dong 2 Danyuan 303 Hao"
                },
                "district": {
                    "type": "string",
                    "example": "SichuanSheng ChengduShi QingyangQu"
                },
                "name": {
                    "type": "string",
                    "example": "Leon Kennedy"
                },
                "phone_number": {
                    "type": "string",
                    "example": "028-87009999"
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/_const.RecipientType"
                        }
                    ],
                    "example": "friend"
                },
                "zip_code": {
                    "type": "string",
                    "example": "610072"
                }
            }
        },
        "form.SendMailForm": {
            "type": "object",
            "properties": {
                "mail_type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/_const.MailType"
                        }
                    ],
                    "example": "plain mail"
                },
                "post_fee": {
                    "type": "number",
                    "example": 1.2
                },
                "post_fee_payment_type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/_const.PostFeePaymentType"
                        }
                    ],
                    "example": "stamps"
                },
                "post_region": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/_const.PostRegion"
                        }
                    ],
                    "example": "domestic local"
                },
                "recipient_address": {
                    "type": "string",
                    "example": "Caotanglu 1 Hao"
                },
                "recipient_district": {
                    "type": "string",
                    "example": "Sichaunsheng Chengdushi Qingyangqu"
                },
                "recipient_name": {
                    "type": "string",
                    "example": "Jimmy Carter"
                },
                "recipient_phone_number": {
                    "type": "string",
                    "example": "13900000001"
                },
                "recipient_type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/_const.RecipientType"
                        }
                    ],
                    "example": "friend"
                },
                "recipient_zip_code": {
                    "type": "string",
                    "example": "610061"
                },
                "send_date": {
                    "type": "string",
                    "example": "2023-05-10T12:00:00Z"
                }
            }
        },
        "m.ContactVo": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "address_secret_part": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/_const.RecipientType"
                },
                "zip_code": {
                    "type": "string"
                }
            }
        },
        "m.SentMailVo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "mail_type": {
                    "$ref": "#/definitions/_const.MailType"
                },
                "post_fee": {
                    "type": "number"
                },
                "post_fee_payment_type": {
                    "$ref": "#/definitions/_const.PostFeePaymentType"
                },
                "post_region": {
                    "$ref": "#/definitions/_const.PostRegion"
                },
                "recipient_address": {
                    "type": "string"
                },
                "recipient_district": {
                    "type": "string"
                },
                "recipient_name": {
                    "type": "string"
                },
                "recipient_phone_number": {
                    "type": "string"
                },
                "recipient_type": {
                    "$ref": "#/definitions/_const.RecipientType"
                },
                "recipient_zip_code": {
                    "type": "string"
                },
                "send_date": {
                    "type": "string"
                }
            }
        },
        "resp.None": {
            "type": "object",
            "properties": {
                "_README!!!!": {
                    "type": "string",
                    "example": "如果您看到这行文字，表示这里的示例 data 字段实际是 null，这里的内容是为上层封装做注释。"
                },
                "code": {
                    "type": "string",
                    "example": "0-成功，1-失败"
                },
                "data": {
                    "type": "string",
                    "example": "实际是 null"
                },
                "msg": {
                    "type": "string",
                    "example": "msg 字段显示相应错误的信息，如数据库查询失败、参数校验失败等"
                },
                "success": {
                    "type": "string",
                    "example": "成功会显示成 true，失败会被设置为 false"
                }
            }
        },
        "resp.Pack-resp_None": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "$ref": "#/definitions/resp.None"
                },
                "msg": {
                    "type": "string",
                    "example": "msg"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "resp.Pack-resp_PagingPack-m_ContactVo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "$ref": "#/definitions/resp.PagingPack-m_ContactVo"
                },
                "msg": {
                    "type": "string",
                    "example": "msg"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "resp.Pack-resp_PagingPack-m_SentMailVo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "$ref": "#/definitions/resp.PagingPack-m_SentMailVo"
                },
                "msg": {
                    "type": "string",
                    "example": "msg"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "resp.PagingPack-m_ContactVo": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/m.ContactVo"
                    }
                },
                "page": {
                    "type": "integer",
                    "example": 10
                },
                "page_size": {
                    "type": "integer",
                    "example": 1
                },
                "total_pages": {
                    "type": "integer",
                    "example": 3
                },
                "total_rows": {
                    "type": "integer",
                    "example": 24
                }
            }
        },
        "resp.PagingPack-m_SentMailVo": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/m.SentMailVo"
                    }
                },
                "page": {
                    "type": "integer",
                    "example": 10
                },
                "page_size": {
                    "type": "integer",
                    "example": 1
                },
                "total_pages": {
                    "type": "integer",
                    "example": 3
                },
                "total_rows": {
                    "type": "integer",
                    "example": 24
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
